services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_nest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules/
  
  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - api
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    command: "http api:3000"
  
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    env_file:
      - ./.env
    environment:
      NODE_ENV: "development"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
    ports:
      - '5432:5432'

    volumes:
      - data-db:/bitnami/postgresql

volumes:
  data-db:
